development: &default
  adapter: postgresql
  encoding: utf8
  database: lti_tool_provider_example_development
  pool: 5
  username: terencee.d@hotmail.com
  password: Scooters1
  host: localhost
  template: template0

test:
  <<: *default
  database: lti_tool_provider_example_test

production:
  <<: *default
  database: lti_tool_provider_example_production
  timeout: 5000
  connect_timeout: 10
