development: &default
  adapter: postgresql
  encoding: utf8
  database: lti_tool_provider_example_development
  pool: 5
  username: hgidoroazkihcq
  password: 0d62c7719bd6e6735cbf6fb7361acafb443fa1c8838e5680d86945a8612819eb
  host: localhost
  template: template0

test:
  <<: *default
  database: lti_tool_provider_example_test

production:
  <<: *default
  database: lti_tool_provider_example_production
  timeout: 5000
  connect_timeout: 10
