development: &default
  adapter: postgresql
  encoding: utf8
  database: d9kvpnupun5tv6
  pool: 5
  username: hgidoroazkihcq
  password: 0d62c7719bd6e6735cbf6fb7361acafb443fa1c8838e5680d86945a8612819eb
  host: ec2-54-163-233-89.compute-1.amazonaws.com
  template: template0

test:
  <<: *default
  database: d9kvpnupun5tv6

production:
  <<: *default
  database: d9kvpnupun5tv6
  timeout: 5000
  connect_timeout: 10
