development: &default
  adapter: postgresql
  encoding: utf8
  database: d9kvpnupun5tv6
  pool: 5
  username: hgidoroazkihcq
  password: Abcd1234
  host: ec2-54-163-233-89.compute-1.amazonaws.com
  template: template0

test:
  <<: *default
  database: d9kvpnupun5tv6

production:
  <<: *default
  database: d9kvpnupun5tv6
  timeout: 5000
  connect_timeout: 10
